name: Next Testing

on:
  push:
    branches:
      - main

jobs: 
  e2e-testing:
    name: App E2E Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21.6.0"
      - name: Install deps
        run: npm ci
      - name: Run e2e tests
        run: npm run e2e:headless